# Generated by Django 3.0.10 on 2023-06-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0003_auto_20230627_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
