# Generated by Django 3.0.10 on 2023-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0004_auto_20230627_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='chalenge_task_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tasks',
            name='challenge_task_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
