# Generated by Django 3.0.10 on 2023-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0006_auto_20230712_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='user_tasks',
            name='point_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
