# Generated by Django 3.0.10 on 2023-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0007_auto_20230718_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tasks',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
