# Generated by Django 3.0.10 on 2023-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0008_auto_20230718_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tasks',
            name='point_earned',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
