# Generated by Django 3.0.10 on 2023-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0009_auto_20230718_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
