# Generated by Django 3.0.10 on 2023-07-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0010_profil_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='publik',
            new_name='challenge',
        ),
    ]
