# Generated by Django 3.0.10 on 2023-07-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0011_auto_20230728_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
