# Generated by Django 3.0.10 on 2023-07-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTamer', '0012_auto_20230729_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='profile_image',
        ),
    ]
